### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by r16h** [RivaanRanawat/flutter-whatsapp-clone#3]
Hi @RivaanRanawat 
Do you have a solution to this problem
![Capture](https://user-images.githubusercontent.com/100477396/180012986-d236325e-4dc4-420e-a7ae-5062b0184f85.PNG)

**Comment by bilalpirzada** [comment]
'sudo' keyword isn't supported in windows. do it without sudo

**Comment by r16h** [comment]
@bilalpirzada Hello
Do you have a solution to this problem.
![1](https://user-images.githubusercontent.com/100477396/184519662-ac808d3a-3055-4c9c-bae7-6e57b8ba88b0.PNG)
![2](https://user-images.githubusercontent.com/100477396/184519664-48752d6a-1aca-44d7-89ed-26e3fb1e7136.PNG)

**Comment by emorilebo** [comment]
Some of the packages used in this project are not supported on flutter web yet.
Try running your project either through an emulator or a physical device @rabee-abu-michael .

**Comment by rabee-abu-michael** [comment]
> Some of the packages used in this project are not supported on flutter web yet. Try running your project either through an emulator or a physical device @rabee-abu-michael .

@emorilebo How can I check if a package is supported or not?

**Comment by r16h** [comment]
> Some of the packages used in this project are not supported on flutter web yet. Try running your project either through an emulator or a physical device @rabee-abu-michael .

@emorilebo I have checked which packages are supported on the flutter web.
![Capture](https://user-images.githubusercontent.com/100477396/187801240-e17f48fb-b38c-4246-940c-f08a7bfa6399.PNG)
![2](https://user-images.githubusercontent.com/100477396/187801253-ee74d536-9912-4172-9a9d-fa2537a1837f.PNG)

**Comment by r16h** [comment]
@emorilebo Hello dear I connected the phone to the Visual Studio code and this problem appeared when I pressed the power button
![Screenshot 2022-09-01 190702](https://user-images.githubusercontent.com/100477396/187991613-583afd3d-8eb4-4382-a36f-c665bb69eb46.png)

**Comment by r16h** [comment]
@RivaanRanawat Dear Rivaan, I want a solution to this problem. When I connect the phone to the software and press RUN, this problem appears
Please don't ignore this problem.
![187991613-583afd3d-8eb4-4382-a36f-c665bb69eb46](https://user-images.githubusercontent.com/100477396/192932652-0ef6c84e-18a2-4fae-9c12-bff107fcba2b.png)

**Comment by RivaanRanawat** [comment]
Same as #7
