### ISSUE TITLE
When I run the project I saw this Error!

### ISSUE THREAD

**Issue by MahmutCanGonul** [RivaanRanawat/flutter-whatsapp-clone#4]
![Screenshot 2022-07-25 200423](https://user-images.githubusercontent.com/75094927/180834441-f42be79d-4753-41ba-9295-8adc58b01073.png)

**Comment by jbridgenet** [comment]
disable "enough_giphy_flutter" in your yaml file

**Comment by RivaanRanawat** [comment]
Since there are no replies to this conversation, I'll close this issue. Feel free to reopen it if the error still persists.

**Comment by moonlitknight** [comment]
Having the same issue. Running SDK 3.3.0
See https://pullanswer.com/questions/error-the-method-flatbutton-isnt-defined-for-the-class-platformbutton
Looks like a transitive dependency on platform_widgets_1.2 in enough_giphy

I confirm that removing enough_giphy_flutter and commenting out giphy functionality fixes the issue.

**Comment by fahadaljohani** [comment]
> disable "enough_giphy_flutter" in your yaml file

thank you too mush jbridge1d it took me two days to figure it out

**Comment by Sarat-1997** [comment]
> ![Screenshot 2022-07-25 200423](https://user-images.githubusercontent.com/75094927/180834441-f42be79d-4753-41ba-9295-8adc58b01073.png)

New flutter version is released so you need to change flat button to text button and raised button to elevated button. If you felt any confusion please refer the below mentioned link:

https://docs.flutter.dev/release/breaking-changes/buttons#restoring-the-original-button-visuals
