### ISSUE TITLE
Phone connection problem

### ISSUE THREAD

**Issue by r16h** [RivaanRanawat/flutter-whatsapp-clone#7]
@RivaanRanawat  Dear Rivaan, I want a solution to this problem. When I connect the phone to the software and press RUN, this problem appears
Please don't ignore this problem.
![187991613-583afd3d-8eb4-4382-a36f-c665bb69eb46](https://user-images.githubusercontent.com/100477396/192932857-8031bc28-2d78-432f-87cd-48f9a8bd3d8f.png)

**Comment by dcagyemang-pros** [comment]
I think it has to do your SHA1 and SHA2 keys, generate new ones and replace

**Comment by RivaanRanawat** [comment]
Has been over a month with no response, so closing this issue.
